# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5fd96eabe3b363bdb490e7489441e69380049ffa5050acb4790d0a81f0ced5dd21c1f4bbcaa2fb1bcdfc3cf22f0342cac574ccd49cae79b335b061f7f63b997

test:
  secret_key_base: c9a48293859ae0295ecae6292fadcda95eaf6ade9dfc4fdd41122f9a77a6c61a1374f37ef6039ee66b60f51c18d07b742893162d66a08e1aea44df28b10d9d0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
